#!/bin/bash
PROJ=`pwd`
# Usage: Call when in top level of project
# copy batch directory to submit node
scp -r $PROJ ikinsella@submit-5.chtc.wisc.edu:~/
echo "$PROJ copied to submit node..."
echo "sshing to submit node to run interactive job"
# On the Submit Node: Use make file to tarzip sourcecode and send it to a build node in an interactive job
# On the Build Node: Use script and make file to automate compilation, cleanup. tarzipped binaries will be sent back to submit node
ssh ikinsella@submit-5.chtc.wisc.edu "cd $PROJ; make sdist; condor_submit -i interactive_build.sub < ./condor_compile.sh"
echo "Interactive Job Completed."
echo "Copying binaries to working directory..."
# Copy tarzipped binaries from submit node to working directory
scp ikinsella@submit-5.chtc.wisc.edu:~/$PROJ/binaries.tar.gz $PROJ/
echo "Binaries successfully transferred"
echo "Cleaning up submit node..."
# Remove everything which was added to the submit node
ssh ikinsella@submit-5.chtc.wisc.edu "rm -rf $PROJ"
echo "SUCCESS! Compiled Binaries: $PROJ/binaries.tar.gz"
