#!/usr/bin/env python
import json
import os

results_dir = os.path.join(os.path.join("{{ user.launch_directory }}", "{{ batch.safe_name }}", "{{ batch.results_dir }}"))
results_files = [file_ for file_ in os.listdir(results_dir)
                 if os.path.isfile(os.path.join(results_dir, file_))]
results = dict()
for result in results_files:  # Copy all jobs, meta, params into universal json
    with open(os.path.join(results_dir, result), 'rb') as readfile:
        results[result.split('.')[0]] = json.load(readfile)
filename = os.path.join(results_dir, "{{ batch.safe_name }}.json")
with open(filename, 'w') as writefile:
    json.dump(results, writefile)
